server:
  port: 7979
spring:
  application:
    name: prometheus-grafana-demo


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG